### PR TITLE
fix zero size issue for buildwidget

### PR DESCRIPTION
**Pull request by keyuan0701**

### CODE REVIEW

**Review by jianhua-git — COMMENTED** [review]
checked

**Comment by gkl54333** [comment]
good

**Review by fjk0401 — COMMENTED** [review]
Good for me

**Review by tianhao-srcn — COMMENTED** [review]
checked

**Review by wb0716 — COMMENTED** [review]
Checked!

**Review by prozanne — APPROVED** [review]
LGTM

**Review by xueli-hu — COMMENTED** [review]
good

**Review by chunhua-liu — APPROVED** [review]

**Comment by keyuan0701** [comment]
checked

**Pull request merged**
