### PR TITLE
download certificate file from tizen and samsung server

### PR DESCRIPTION
**Pull request by keyuan0701**

### CODE REVIEW

**Review by jianhua-git — COMMENTED** [review]
checked

**Comment by gkl54333** [comment]
gd

**Review by wb0716 — COMMENTED** [review]
Checked!

**Review by xueli-hu — COMMENTED** [review]
good

**Review by tianhao-srcn — COMMENTED** [review]
checked

**Review by xujiangang-git — COMMENTED** [review]
checked

**Review by chunhua-liu — APPROVED** [review]

**Pull request merged**
